### ISSUE TITLE
Issue with composition

### ISSUE THREAD

**Issue by KKreutzmann** [VirtualPlanetaryLaboratory/vplanet#199]
in magmoc.h file line 76, the mass fraction of MgO in the mantle is defined as 0.0367, which is very low for a mantle peridotite. I think the MASSFRACMGO is meant to be 0.367 instead? Which is more consistent with papers.

I have no real experience programming with c, and cannot get the 'makefile' to compile with the new values.

extra q: is there any way I can make the core a parameter option in the body files also?
I'm doing my master's in early terrestrial mo evolution, and would like the opportunity to change the core size. It can be relative to Earth, like with planet mass and radius, if that will make it easier for me.
Thank you for your troubles.

**Comment by RoryBarnes** [comment]
Thanks for your comment. I'm not sure the origin of that value. Patrick Barth and Ludmila Carone might have a better sense of where that number comes from. Currently the core can not be coupled to the MO model, but we are working on it.

Can you describe in more detail the problems you're having with the makefile? Is it compiling when MASSFRACMGO is set to 0.0367, but not when 0.367?

**Comment by LudmilaCarone** [comment]
Dear KKreutzmann, I will have a look next Monday and come back to you with some ideas.

**Comment by KKreutzmann** [comment]
Hi Rory,
It's just in general that I cannot run the makefile. I'm not very abt in c language or programming in general, and I'm currently using the vplanet code in my master's thesis, and I have my supervisor try and figure out how to run it as well, as we might have to change some values that are locked in the .h files. I've tried to have it run in anaconda but it halts already in the second line. 
So the problem might be entiredly on my end.

**Comment by KKreutzmann** [comment]
Thank you very much Ludmila, I appreciate the effort.

**Comment by RoryBarnes** [comment]
There are a couple different ways to [install the code that don't involve the Makefile](https://virtualplanetarylaboratory.github.io/vplanet/install.html). Have you tried those? You can also try cloning the repository and then run "make legacy". That will build a C-only version in the bin folder. Please let me know if none of those 3 methods work.

**Comment by KKreutzmann** [comment]
It works fine installing the code with the 'develop' method. Thank you very much.
Will I now be able to change the values in the h files and have new values that way? Or do I still need to compile them before I can use the new values?

**Comment by RoryBarnes** [comment]
Great! If you want to test other values in the .h files, you will need to re-compile every time you make a change.

**Comment by LudmilaCarone** [comment]
Does this mean that this issue has been resolved?

**Comment by KKreutzmann** [comment]
Yes, I can now change the parameters to fit my needs. 
Though there still might be an issue with the composition in the magmoc.h file, if that is how you calculate viscousflow to determine when the convective regime changes from turbulent to a more solid state.

**Comment by KKreutzmann** [comment]
Hi, sorry for reopening this issue.
I've tried to change the radcoreearth value in the magmoc.h file and run the setup.py again, but i see no changes. I still cannot use the makefile option to compile either. It might be because I use windows?
Do you have any solutions for me?

**Comment by RoryBarnes** [comment]
No need to apologize; I'm sorry it's still not working for you. That parameter won't do much to change the evolution, unless you change it by a significant amount. Can you confirm a few simple things for me: Does the timestamp for the executable change after you rerun setup.py? Are you sure there are no aliases that point to a different executable? How are you confirming that no change has occurred? One thing to try is to change RADCOREEARTH to be 3-5 times larger and check the output of RadioPower, as it depends on the core radius. Are you running from the DOS prompt/Powershell, or a Linux emulator? 

We'll figure this out!

**Comment by KKreutzmann** [comment]
Thank you very much.
After I run setup.py only the h file looks updated, and it might be because I've saved the changes with ctr s.
I've tried to change RADCOREEARTH to have a similar corefraction to Mercury, but that does nothing. (5.415e6) about 85 % of total planetary radius.
I'm pretty sure I'm running a Linux emulator.

**Comment by LudmilaCarone** [comment]
If you want to run Mercury I have a suspicion why your changes in core radius does not end up during the simulation. It may be because of these lines of the code inside InitalizeBodyMagmOc in magmoc.c

>>Code snippet start
dSolidRadiusLocalLow =
        body[iBody].dRadius -
        ((BLOWPRESSURE - body[iBody].dPotTemp) /
         (body[iBody].dGravAccelSurf *
          (body[iBody].dPotTemp * THERMALEXPANCOEFF / SILICATEHEATCAP -
           ALOWPRESSURE * body[iBody].dManMeltDensity)));
  dSolidRadiusLocalHigh =
        body[iBody].dRadius -
        ((BHIGHPRESSURE - body[iBody].dPotTemp) /
         (body[iBody].dGravAccelSurf *
          (body[iBody].dPotTemp * THERMALEXPANCOEFF / SILICATEHEATCAP -
           AHIGHPRESSURE * body[iBody].dManMeltDensity)));
  body[iBody].dSolidRadius = fmin(dSolidRadiusLocalLow, dSolidRadiusLocalHigh);

  if (body[iBody].dSolidRadius < body[iBody].dCoreRadius) {
    body[iBody].dSolidRadius = body[iBody].dCoreRadius;
  }
  
 >> Code snippet end.

You need to know that body[iBody].dCoreRadius is here initially the core/radius fraction that you specified (as given in the paper). However, we always assume that our magma ocean starts fully convective  And that is ensured by the line
>> body[iBody].dSolidRadius = fmin(dSolidRadiusLocalLow, dSolidRadiusLocalHigh);

I would guess, that since Mercury's core is so large, it violates our "start with a fully convective magma ocean"  condition, which then automatically overwrites body[iBody].dCoreRadius to set it to the lower value to allow to start with the fully convective magmocean again. ( body[iBody].dSolidRadius = body[iBody].dCoreRadius;) 
Because we require mantle melt fraction initially as = 1. 

Can you check that this is what is happening? E.g can you run a debugger? Or insert in the code print statements in the function InitializeBodyMagmOc to give you RADCOREEARTH and what is assumed as solid core size? Generally, as a tipp. Check carefully what is done in InitializeBodyMagmOc. In this function the properties of your current magma ocean are defined. 

If that is indeed what is happening then I would advise you to go into magmoc.c and to comment out the following lines in magmoc.c inside the function InitalizeBodyMagmOc

 if (body[iBody].dSolidRadius < body[iBody].dCoreRadius) {
    body[iBody].dSolidRadius = body[iBody].dCoreRadius;
  }

Can you check then what the initial melt fraction is? My guess is that in your version of magmoc it should work to start with a lower mantle melt fraction than 1. But we never tested this.

**Comment by LudmilaCarone** [comment]
Ok, I deleted the previous post because I think that this could be confusing. 

>>I've tried to change RADCOREEARTH to have a similar corefraction to Mercury, but that does nothing

What do you mean "it does nothing"? What do you want to change? The depth of the initial magma ocean? 

I think in your case, this value can be best set with dDepthMO  in units of kms in your mercury.in file like this:

dDepthMO                -2000     #Initial magma ocean depth in km, here according to
                                  # Elkins-Tanton (2008) as 2000 km
                                  
Due to the large size of Mercury core radius it may be that otherwise another intrinsic function sets in that tries to ensure that the magma ocean is deep enough to allow for full convection. Setting dDepthMO should overwrite this and give you the correct value.

Careful however!
You should still set RADCOREEARTH as well to the correct value of Mercury's core radius, because the modules RADHEAT and (I think also) EQTIDE need the correct RADCOREARTH.

If you still have problems you can contact me via carone@mpia and we can talk through your issues in more depth.

**Comment by KKreutzmann** [comment]
Hi Ludmila, I tried sending you an email, but I've received a message that it couldn't be sent.

I've tried to change the RADCOREEARTH to the value I want for a mercury-type planet, and also inserted the dDepthMO in the bodyfile. It seems that the dDepthMO is helping, though I'm unsure as to how I can be sure that the change to the coresize is in effect. Is there any way I can check to see that?
When I've changed the value and run the setup.py delevop command it doesn't seem to update any of the files in the folder (no new timestamp after setup, only when I've saved the changes in the file).
I'm calculating the solidification time by changing parameters and see their effects. So basically, I'm doing a parametric study of the code and comparing it to other results/values from papers.

I still get errors when I try to run the makefile to update the values in the magmoc.h file, and it doesn't seem to be updating either when I run the setup.py develop.

Thank you very much.
Karen Kreutzmann

**Comment by LudmilaCarone** [comment]
Dear Karen,

you have to put the extension for Germany at the end of the full email. It is this one carone@mpia.de

You can check the setting of the core and soldification radius in the log files once the simulation is running. In the log file associated with your planet, the main planetary parameters at the beginning and the end of the simulation (if terminated successful) are listed. But even if your simulation does not run through, you should get there at least what the system sets at the beginning of the simulation. 

 I have to see the errors that you get when you run makefile to have any idea why you have problems.

**Comment by LudmilaCarone** [comment]
It is getting more and more confusing. I was able to generate a 1000 km thick initial magma ocean for Earth with dDepthMO just fine.

We are checking now if Karan is using an older version of magmoc or has some other issues.

**Comment by KKreutzmann** [comment]
My supervisor and I found a solution to the problem. Thank you all for your help!
